// ================================================
// Radar Room — Articles Data
// ================================================

export const articles = [
  { id: 1, slug: "who-can-donate-blood", category: "donation", tag: "Blood Donation", title: "Who Can Donate Blood? The Complete Eligibility Guide", excerpt: "Most healthy adults between 18–65 weighing over 50kg can donate. Learn the full criteria including medical conditions, medications, and travel restrictions.", readTime: "4 min read", isNew: true, locked: false },
  { id: 2, slug: "blood-donation-myths-debunked", category: "myths", tag: "Myths & Facts", title: "10 Common Blood Donation Myths — Debunked", excerpt: "\"Donating blood makes you weak.\" \"You can get infected.\" We bust the most persistent misconceptions with science-backed facts.", readTime: "6 min read", isNew: true, locked: false },
  { id: 3, slug: "abo-rh-blood-groups-explained", category: "bloodgroups", tag: "Blood Groups", title: "ABO & Rh Blood Group Systems Explained", excerpt: "Why does blood type matter? A deep dive into the ABO and Rh systems, compatibility charts, and why O-negative is called the universal donor.", readTime: "5 min read", isNew: false, locked: false },
  { id: 4, slug: "what-happens-blood-after-donation", category: "hematology", tag: "Hematology", title: "What Happens to Your Blood After Donation?", excerpt: "From the moment blood leaves your arm to when it reaches a patient — the full journey through testing, processing, and storage.", readTime: "7 min read", isNew: false, locked: true },
  { id: 5, slug: "artificial-blood-science-2025", category: "research", tag: "Medical Research", title: "Artificial Blood: Where Does the Science Stand in 2025?", excerpt: "Researchers are making breakthroughs in synthetic blood substitutes. We explore the latest clinical trials and what it means for global blood supply.", readTime: "8 min read", isNew: true, locked: true },
  { id: 6, slug: "48-hour-recovery-after-donating", category: "donation", tag: "Blood Donation", title: "The 48-Hour Recovery: What to Eat and Do After Donating", excerpt: "Iron-rich foods, hydration tips, and activities to avoid — everything you need to bounce back quickly and feel your best after donation.", readTime: "3 min read", isNew: false, locked: false },
  { id: 7, slug: "india-blood-bank-crisis", category: "news", tag: "Latest News", title: "India's Blood Bank Crisis: A State-by-State Analysis", excerpt: "A new report reveals severe shortages in rural blood banks. REDDAR's role in bridging the gap through real-time donor networks.", readTime: "6 min read", isNew: true, locked: true },
  { id: 8, slug: "platelet-vs-whole-blood-donation", category: "hematology", tag: "Hematology", title: "Platelet Donation vs. Whole Blood: Key Differences", excerpt: "Platelets save cancer patients and trauma victims. Learn how apheresis donation works and why it's critically underutilized in India.", readTime: "5 min read", isNew: false, locked: true },
  { id: 9, slug: "rarest-blood-types-world", category: "bloodgroups", tag: "Blood Groups", title: "The Rarest Blood Types in the World", excerpt: "Beyond ABO — the Bombay phenotype, Golden Blood (Rh-null), and other ultra-rare types that have only been found in a handful of humans.", readTime: "4 min read", isNew: false, locked: true },
];